spring:
  datasource:
    username: root
    initialization-mode: never
    url: jdbc:mysql://localhost:3306/yes24
#    data: classpath:/data.sql
    password: '@Jesi9520'
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    com:
      tutorial:
        springboot: DEBUG
  path: logs